version: '2'
services:
  nginx:
    build: DockerFileNginx
    ports:
      - "80:80"
    volumes:
      - /var/www:/var/www
    tty: true
  mysql:
    build: DockerFileMysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    tty: true