version: '2'
services:
  nginx:
    build: DockerFileNginx
    ports:
      - "80:80"
    volumes:
      - /var/www:/var/www
    tty: true
  mysql:
    build: DockerFileMysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    tty: true
  postgre:
    build: DockerFilePostgre
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/9.5/main:/var/lib/postgresql/9.5/main
    tty: true
